### ISSUE TITLE
Getting Error While Creating a new React Application

### ISSUE THREAD

**Issue by aliarslanansari** [wednesday-solutions/react-floki#26]
```
C:\Users\Ali\Desktop\hello> npm install -g react-floki
C:\Users\Ali\Desktop\hello> react-generate init hello_world
Cloning into 'react-template'...
json: error: ENOENT: no such file or directory, open 'hello_world/package.json'
json: error: ENOENT: no such file or directory, open 'hello_world/package.json'
json: error: ENOENT: no such file or directory, open 'hello_world/package.json'
json: error: ENOENT: no such file or directory, open 'hello_world/package.json'
fatal: not a git repository (or any of the parent directories): .git
child_process.js:651
    throw err;
    ^

Error: spawnSync C:\Users\Ali\AppData\Roaming\npm\node_modules\react-floki\node_modules\.bin\plop ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:616:24)
    at Object.execFileSync (child_process.js:643:15)
    at execShell (C:\Users\Ali\AppData\Roaming\npm\node_modules\react-floki\bin\react-generate.js:24:16)
    at Object.<anonymous> (C:\Users\Ali\AppData\Roaming\npm\node_modules\react-floki\bin\react-generate.js:77:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\react-floki\\node_modules\\.bin\\plop',
  path: 'C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\react-floki\\node_modules\\.bin\\plop',
  spawnargs: [
    '-f',
    '--plopfile',
    'C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\react-floki\\generators\\index.js',
    'webpackBaseBabel'
  ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
PS C:\Users\Ali\Desktop\hello> cd .\hello_world\
```
I'm not getting what i'm doing wrong,
please help

**Comment by alichherawalla** [comment]
This issue is windows specific, we're currently only supporting UNIX based systems
